# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802034e745bdfc99151c615c8082bbdb6523a1314030611833c1b53f9c8fb1de13e2bd329838b25de5611c95a571ef9e735788f7276e6020e22348c9d1b7847f

test:
  secret_key_base: a87377c561d4b1513b36ae51e4ead7ab78416db7b7bb0030f8dda1ec7370dbedca8efa7f73507fcd6f217accae5be782f597d3f1abd2ddd4dde9e94396800175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
